# Generated by Django 5.0.6 on 2024-07-05 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewlike',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewlike',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='like_users',
            field=models.ManyToManyField(related_name='like_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ReviewDislike',
        ),
        migrations.DeleteModel(
            name='ReviewLike',
        ),
    ]
